
import React from 'react';

const Disclaimer: React.FC = () => {
    return (
        <div className="mt-8 p-4 bg-yellow-900/30 border-2 border-yellow-600 rounded-lg text-sm text-yellow-200">
            <div className="font-bold text-yellow-300 mb-2">⚠️ CRITICAL LEGAL & SAFETY WARNING</div>
            <ul className="list-disc list-inside space-y-1 text-xs sm:text-sm">
                <li>This is a conceptual tool for educational purposes only. It does not interact with real hardware.</li>
                <li>Transmitting radio frequencies or jamming signals is illegal in most jurisdictions without proper authorization and can have severe consequences.</li>
                <li>The data and analysis presented are simulated and/or generated by AI for illustrative purposes. They should not be used for real-world decisions.</li>
                <li>Always comply with all local, national, and international laws regarding telecommunications and privacy.</li>
            </ul>
        </div>
    );
};

export default Disclaimer;
