import React from 'react';
import { GhostIcon } from './icons';

interface FirstRunModalProps {
    onClose: () => void;
}

const FirstRunModal: React.FC<FirstRunModalProps> = ({ onClose }) => {
    return (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-slate-900 border-2 border-cyan-500/50 rounded-2xl w-full max-w-2xl shadow-2xl shadow-cyan-900/30">
                <div className="p-6 sm:p-8 space-y-6">
                    <div className="flex items-center gap-4">
                        <GhostIcon className="w-12 h-12 text-cyan-400" />
                        <div>
                            <h1 className="text-2xl sm:text-3xl font-bold text-slate-100">Welcome to Ghost Veil Protocol</h1>
                            <p className="text-sm sm:text-base text-slate-400">Cognitive Liberty & Signal Integrity Framework</p>
                        </div>
                    </div>

                    <div className="p-4 bg-yellow-900/30 border-2 border-yellow-600 rounded-lg text-sm text-yellow-200">
                        <div className="font-bold text-yellow-300 mb-2">⚠️ PLEASE READ: CRITICAL WARNING</div>
                        <p className="text-xs sm:text-sm">
                            This is a conceptual, non-functional application for educational purposes. The data is generated by the system's AI. <strong>It does not interact with any real hardware, transmit signals, or perform any real-world scanning or protection.</strong> Attempting to build or use real-world equivalents may be dangerous and is illegal in most jurisdictions.
                        </p>
                    </div>

                    <p className="text-sm text-slate-300">
                        This interface is an advanced framework for detecting and neutralizing threats to cognitive liberty. Explore the tools, monitor the spectrum, and engage with the AI-driven threat analysis systems.
                    </p>

                    <button
                        onClick={onClose}
                        className="w-full bg-gradient-to-r from-cyan-600 to-blue-700 hover:from-cyan-700 hover:to-blue-800 px-6 py-3 rounded-lg font-bold text-lg transition-all duration-300 shadow-lg shadow-blue-900/50"
                    >
                        Acknowledge & Continue
                    </button>
                </div>
            </div>
        </div>
    );
};

export default FirstRunModal;
